// packages/svelte/src/lib/Img.svelte
<script lang="ts">
	import type { HTMLImgAttributes } from "svelte/elements";

	/**
	 * Img Component
	 *
	 * @component
	 * @example
	 * <Img></Img>
	 */

	interface $$props extends HTMLImgAttributes {
		src: string;
		alt: string;
		loading: "eager" | "lazy";
	}

	/** @props image url or path */
	export let src: string = "";
	/** @props image url or path */
	export let alt: string = "";
	/** @props image url or path */
	export let loading: "eager" | "lazy" = "lazy";
</script>

<img {src} {alt} {loading} {...$$restProps} />

// src/components/Img.vue
<template>
	<component :is="imageComponent" v-bind="props" />
</template>

<script setup lang="ts">
	import { PropType, computed, inject } from "vue";

	import { iPluginOptions } from "../types";

	/**
	 * Img Component
	 *
	 * @component
	 * @example
	 * <Img></Img>
	 */

	const props = defineProps({
		/**
		 * image url or path
		 */
		src: {
			type: String,
			default: null,
		},
		alt: {
			type: String,
			default: null,
		},
		loading: {
			type: String as PropType<"eager" | "lazy">,
			default: "lazy",
		},
	});

	const vueComponentSystem = inject<iPluginOptions>("vueComponentSystem");

	const imageComponent = computed(() => {
		return vueComponentSystem?.imageComponent || "img";
	});
</script>
