// src/components/Wrapper.vue
<template>
	<Component :is="el" v-if="render">
		<slot></slot>
	</Component>
	<slot v-else></slot>
</template>

<script setup lang="ts">
	import { Component, DefineComponent, PropType } from "vue";

	/**
	 * Wrapper Component
	 *
	 * @component
	 * @example
	 * <Wrapper></Wrapper>
	 */

	defineProps({
		/**
		 * Wheter or not render the wrapper
		 */
		render: {
			type: Boolean,
			required: true,
		},
		/**
		 * Component or tag to render
		 */
		el: {
			type: [String, Object] as PropType<Component<any> | DefineComponent<any> | string>,
			default: "div",
		},
	});
</script>

// packages/svelte/src/lib/Wrapper.svelte
<script lang="ts">
	import type { ComponentType } from "svelte";

	/**
	 * Wrapper Component
	 *
	 * @component
	 * @example
	 * <Wrapper></Wrapper>
	 */

	/** @props Wheter or not render the wrapper */
	export let render: boolean;
	/** @props Component or tag to render */
	export let el: ComponentType<any> | string = "div";
</script>

{#if render}
	{#if typeof el == "string"}
		<svelte:element this={el}>
			<slot />
		</svelte:element>
	{:else}
		<svelte:component this={el}>
			<slot />
		</svelte:component>
	{/if}
{:else}
	<slot />
{/if}
